package view

// Every user-visible string of the views (GUI spec 3.6). Sentences with
// variable parts are format strings.

// Application and shell.
const (
	appName        = "RestoreSafe"
	navCreate      = "Create backup"
	navRestore     = "Restore backup"
	navSettings    = "Settings"
	statusChecking = "Checking…"
)

// Hero titles and lines (GUI spec 5, figure 5.3).
const (
	heroProtected          = "Your folders are protected"
	heroEmpty              = "Create your first backup"
	heroReady              = "Ready to back up"
	heroFacts              = "%s · Last backup %s"
	heroMore               = " · and %d more problems"
	heroMoreOne            = " · and 1 more problem"
	heroChecking           = "Checking your backups…"
	heroConfigInvalid      = "RestoreSafe can't read its configuration"
	heroConfigLine         = "Check config.yaml, then start RestoreSafe again."
	heroReloadTitle        = "config.yaml can't be loaded"
	heroReloadLine         = "RestoreSafe keeps using the previous settings. Fix config.yaml, then click Refresh. %s"
	heroDirUnreachable     = "The backup directory isn't reachable"
	heroDirUnreachLine     = "%s doesn't respond. Check the drive or the network connection."
	heroDirNotWritable     = "RestoreSafe can't write to the backup directory"
	heroDirNotWritLine     = "Check the permissions of %s."
	heroSourceMissing      = "%s can't be found"
	heroSourceMissLine     = "Connect the drive, or remove the folder from config.yaml."
	heroSourceInvalid      = "%s can't be used"
	heroSourceInvLine      = "Check the folder, or remove it from config.yaml. The details say why."
	heroBaseMissingOne     = "A backup of %s can't be restored"
	heroBaseMissing        = "%d backups of %s can't be restored"
	heroBaseMissingLine    = "Their full backup (chain %s) %s. Restore its FULL files from your copy, or delete the DIFF files of %s."
	heroBaseMissingLineOne = "Its full backup (chain %s) %s. Restore its FULL files from your copy, or delete the DIFF files of %s."
	heroSetUnusable        = "A backup of %s can't be used"
	heroSetUnreadable      = "A backup of %s can't be read"
	heroSetFullLine        = "The full backup of %s (chain %s) %s. %s"
	heroSetDiffLine        = "Differential %d of %s (chain %s) %s. %s"
	faultGone              = "is missing"
	faultIncomplete        = "is incomplete"
	faultPartMissing       = "is missing part %03d"
	faultPartsMissing      = "is missing %d parts (%03d to %03d)"
	faultRenamed           = "has renamed files"
	faultUnreadable        = "can't be read"
	faultDamaged           = "is damaged"
	remedyFromCopy         = "Restore its files from your copy, or delete them."
	remedyNames            = "Restore the original file names."
	remedyDrive            = "Check the drive, then click Refresh."
	heroVerifyFailed       = "A backup of %s is damaged"
	heroVerifyLine         = "The verification found an error. Create a new backup, and don't rely on the damaged one."
	heroOverdue            = "Your last backup is %d days old"
	heroOverdueLine        = "Your reminder limit is %d days · Last backup %s"
	heroNotBackedUp        = "%s has no backup yet"
	heroNotBackedUpLine    = "Back up now to protect it."
	heroSkippedOne         = "1 file in %s wasn't backed up"
	heroSkipped            = "%d files in %s weren't backed up"
	heroSkippedLine        = "They couldn't be read. Older backups of %s are kept until a backup without skipped files succeeds."
	heroIncomplete         = "An unfinished backup of %s is newer than its last complete one"
	heroIncompleteLine     = "Probably a crash. The log of that run tells what happened."
	heroSpaceLow           = "The backup directory is running out of space"
	heroSpaceLowLine       = "A full backup of all folders needs about %s; %s are free."
	heroArgon2             = "A key setting was too high and was capped"
	heroArgon2Line         = "Lower the value in config.yaml."
)

// Buttons and links; & marks the access key.
const (
	buttonBackUp       = "&Back up now…"
	buttonCheckAgain   = "Check &again"
	buttonRefresh      = "Re&fresh"
	buttonEditConfig   = "&Edit config"
	buttonShowBackups  = "&Show backups"
	reasonBlockedCheck = "Fix the problems the check found first."
)

// Create backup cards (GUI spec 5, figure 5.1).
const (
	cardFolders      = "Folders to back up"
	cardStorage      = "Backup directory"
	columnLastBackup = "Last backup"
	columnNextBackup = "Next backup"
	tipNextBackup    = "Next backup %s: %s"
	columnPath       = "Path"
	folderNoBackup   = "no backup yet"
	folderMissing    = "Can't be found"
	folderInvalid    = "Can't be used"
	folderDuplicate  = "Listed twice; backed up once"
	storageUsed      = "%s of %s used"
	storageUnknown   = "Free space unknown"
	legendBackups    = "Backups %s"
	legendOther      = "Other %s"
	legendFree       = "Free %s"
	storageEstimate  = "A full backup of all folders needs about %s"
	laterFailed      = "The backup of %s failed; the Restore backup page has its log."
	laterCancelled   = "The backup of %s was cancelled before it backed up a folder."
	lastCancelled    = "The backup of %s was cancelled; not every folder was backed up."
	cardKeys         = "Keys"
	keysCreated      = "Created %s"
	keysSpare        = "2 YubiKeys"
	keysRecovery     = "recovery code"
	keysNone         = "Your first backup creates your keys."
	keysNewNeeded    = "Your next backup creates new keys: %s"
	yubiKeyConnected = "YubiKey connected"
	yubiKeyMissing   = "YubiKey not connected"
	folderOne        = "1 folder"
	folderMany       = "%d folders"
	badgeFull        = "FULL"
	badgeDiff        = "DIFF %d"
	badgeFullName    = "Full backup"
	badgeDiffName    = "Differential %d"
	typeDiff         = "DIFF"
	typeFull         = "FULL"
)

// Window, interim pages and dialogs.
const (
	titleFormat          = "%s %s"
	titleWithConfig      = "%s %s · %s"
	settingsConfigFile   = "Configuration file"
	settingsBackupDir    = "Backup directory"
	buttonEditConfigFile = "&Edit config.yaml"
	buttonOpenFolder     = "&Open in Explorer"
	buttonClose          = "Close"
)

// ButtonClose is the label of a dialog's close button.
const ButtonClose = buttonClose

// Backup plan (GUI spec 6.1).
const (
	planTitle              = "Back up"
	planHeading            = "Back up %s to %s"
	planNewKeys            = "New keys will be created: %s. Every folder gets a full backup."
	planWhyDiff            = "Based on the full backup of %s"
	planEstimateNote       = "Differential sizes are estimates; moved or renamed files are stored again."
	planSpace              = "Space"
	planUnlock             = "Unlock"
	planAfterwards         = "Afterwards"
	spaceNeeded            = "About %s needed"
	spaceNeededUpTo        = "About %s needed, up to %s"
	spaceFree              = " · %s free"
	spaceFreeUnknown       = " · free space unknown"
	unlockPassword         = "Password"
	unlockTouch            = "One YubiKey touch"
	unlockTouchAndPassword = "One YubiKey touch, then your password"
	unlockNewPassword      = "new password"
	unlockRegisterOne      = "register your YubiKey (2 prompts)"
	unlockRegisterTwo      = "register 2 YubiKeys (4 prompts)"
	unlockRecoveryCode     = "store a recovery code"
	afterVerify            = "Verify each new backup."
	afterRemove            = "Remove %s (%s)."
	afterRemoveIfOK        = "If the backup succeeds, remove %s (%s)."
	afterKeepAll           = "Nothing is removed; old backups are kept."
	afterKeepOne           = "Nothing is removed (keeps 1 chain per folder)."
	afterKeepChains        = "Nothing is removed (keeps %d chains per folder)."
	afterNothing           = "Nothing is removed."
	oldBackupOne           = "1 old backup"
	oldBackupMany          = "%d old backups"
	removeDiffOne          = "1 differential"
	removeDiffs            = "%d differentials"
	removeFullAndDiffs     = "%s: full backup of %s and %s, %s"
	removeFull             = "%s: full backup of %s, %s"
	removeOnlyDiffs        = "%s: %s, %s"
	linkShowDetails        = "Show details"
	linkShowRemoved        = "Show what's removed"
	buttonStart            = "&Start"
	buttonFullInstead      = "&Full backup instead"
	buttonBackToPlan       = "&Back to plan"
	buttonNewKeys          = "&New keys + full backup…"
	buttonCancel           = "Cancel"
	lockPassword           = "a new password"
	lockYubiKey            = "a new YubiKey registration"
	lockRecoveryCode       = "a new recovery code"
	newKeysInstruction     = "Create new keys?"
	newKeysContent         = "Every folder gets a full backup, locked with %s. Your current keys keep opening your older backups, but not the new ones.\n\nUse this to change your password, replace a lost YubiKey, or get a new recovery code."
	newKeysYes             = "Create keys"
	newKeysNo              = "Keep current keys"
)

// Progress card, Folders card while running, status bar and cancel
// dialogs (GUI spec 6.2, 6.4).
const (
	titleBackingUp         = "Backing up"
	titleRestoring         = "Restoring"
	titleVerifying         = "Verifying"
	stepUnlock             = "Unlock keys"
	stepCreateKeys         = "Create keys"
	stepBackUp             = "Back up"
	stepVerify             = "Verify"
	stepCleanUp            = "Clean up"
	stepRestore            = "Restore"
	stepCounted            = "%s %d of %d"
	progressUnlocking      = "Unlocking keys…"
	progressPreparing      = "Preparing the backup plan…"
	progressCheckPlan      = "Check the plan, then start the backup."
	progressCreatingKeys   = "Creating your keys…"
	progressSecurityPrompt = "Unlocking keys… Follow the Windows Security prompt."
	progressCancelling     = "Cancelling… RestoreSafe finishes the current step and cleans up."
	progressFolder         = "%s · %s"
	progressVerifying      = "Verifying %s"
	progressCleaningUp     = "Removing old backups…"
	progressBytes          = "%s of %s"
	progressSpeed          = "%s/s"
	typeDifferentialN      = "differential %d"
	typeFullBackup         = "full backup"
	linkShowLog            = "Show log"
	buttonCancelling       = "Cancelling…"
	folderWaiting          = "Waiting"
	folderDone             = "Done, %s"
	folderBackingUp        = "Backing up"
	folderBackingUpPct     = "Backing up, %d%%"
	folderCancelled        = "Cancelled"
	folderFailed           = "Failed"
	cancelBackup           = "Cancel this backup?"
	cancelBackupContent    = "Folders already backed up in this run are kept. The folder being backed up now is discarded. No old backups are removed."
	cancelRestore          = "Cancel this restore?"
	cancelRestoreContent   = "Folders restored so far are kept. The folder being restored now stays incomplete; don't use it as a full copy."
	cancelVerify           = "Cancel this verification?"
	cancelVerifyContent    = "Nothing is changed. The backups verified so far keep their result."
	closeInstruction       = "Close RestoreSafe?"
	buttonCancelBackup     = "Cancel backup"
	buttonCancelRestore    = "Cancel restore"
	buttonCancelVerify     = "Cancel verification"
	buttonKeepRunning      = "Keep running"
	buttonKeepRestoring    = "Keep restoring"
	buttonCancelAndClose   = "Cancel and close"
)

// Result card (GUI spec 6.3).
const (
	buttonDone              = "&Done"
	buttonShowRunLog        = "Show &log"
	buttonCancelRun         = "&Cancel"
	nounBackup              = "Backup"
	nounVerification        = "Verification"
	nounRestore             = "Restore"
	resultFinished          = "%s finished"
	resultBackedUp          = "%s backed up"
	resultRestored          = "%s restored"
	resultCanRestore        = "The backup of %s can be restored"
	resultCanRestoreFolders = "%s can be restored"
	resultCanRestoreSome    = "%s from the backup of %s can be restored"
	resultDamaged           = "Damage found in the backup of %s"
	resultWithWarningOne    = " with 1 warning"
	resultWithWarnings      = " with %d warnings"
	resultOtherProblem      = "Another backup has a problem; the Restore backup page shows it."
	resultOtherProblemBelow = "Another backup has a problem; see below."
	resultCancelled         = "%s cancelled"
	resultNotStarted        = "%s didn't start"
	resultFailed            = "%s failed"
	resultSummary           = "Done in %s."
	resultSummarySize       = "%s in %s."
	resultVerified          = "Verified."
	resultSkippedOne        = "1 file in %s couldn't be read and wasn't backed up."
	resultSkipped           = "%s files in %s couldn't be read and weren't backed up."
	resultStaleOne          = "1 file in %s couldn't be read; this backup keeps its older version from the full backup."
	resultStale             = "%s files in %s couldn't be read; this backup keeps their older version from the full backup."
	resultOlderKept         = "Older backups of %s are kept."
	resultVerifyFailed      = "The verification of %s found an error. No old backups were removed."
	resultRemovedOne        = "Removed 1 old backup (%s)."
	resultRemoved           = "Removed %d old backups (%s)."
	resultCleanupFailed     = "Old backups couldn't be removed; the log says why."
	resultCleanupHeld       = "Old backups were kept, as some backup information couldn't be read."
	resultCheckedOne        = "Checked 1 folder in %s."
	resultChecked           = "Checked %s in %s."
	resultCheckedBaseOne    = "Checked 1 folder in %s, including the full backup it's based on."
	resultCheckedBases      = "Checked %s in %s, including the full backups they're based on."
	resultEveryFile         = "Every file matched its checksum."
	resultOtherWarningOne   = "1 other warning is in the log."
	resultOtherWarnings     = "%d other warnings are in the log."
	resultNothingChanged    = "Nothing was changed."
	resultNothingBackedUp   = "Nothing was backed up."
	resultBackedUpOne       = "%s was backed up."
	resultBackedUpMany      = "%s were backed up."
	resultUnfinished        = "The unfinished %s backup was removed."
	resultNoneRemoved       = "No old backups were removed."
)

// Credential dialogs (GUI spec 9).
const (
	unlockTitle          = "Unlock your backups"
	unlockIntro          = "Enter the password of your backups."
	unlockRecoveryIntro  = "Enter your recovery code as it is written on your note."
	unlockWithYubiKey    = "Unlock with your YubiKey. Windows asks you to touch it."
	unlockWithBoth       = "Unlock with your YubiKey and your password. Windows asks for the YubiKey first."
	unlockOtherKeys      = "Backup %s uses different keys (created %s). Authenticate with the credentials of those keys."
	linkUseRecovery      = "Use your recovery code instead"
	fieldPassword        = "Password"
	fieldConfirmPassword = "Confirm password"
	fieldRecoveryCode    = "Recovery code"
	buttonUnlock         = "Unlock"
	buttonNext           = "Next"
	buttonContinue       = "Continue"
	buttonStored         = "I have stored it"
	createKeysTitle      = "Create your keys"
	recoveryTitle        = "Your recovery code"
	stepOf               = "%s · Step %d of %d"
	newPasswordIntro     = "Choose a password for your backups."
	newPasswordHint      = "You need it for every backup and every restore."
	newPasswordHintN     = "At least %d characters. You need it for every backup and every restore."
	stepsPrefix          = "Steps: "
	stepNamePassword     = "password"
	stepNameYubiKey      = "register your YubiKey"
	stepNameSpare        = "register your spare YubiKey"
	stepNameRecovery     = "recovery code"
	spareIntro           = "Remove your YubiKey and connect your spare YubiKey."
	spareHint            = "Windows then asks twice for the PIN of the spare YubiKey."
	recoveryIntro        = "Store this code in your password manager or write it down now. It's shown only once and opens your backups on its own."
	recoveryNote         = "Keep it in a safe place, never next to your backups or unencrypted on this computer."
	attemptsLeft         = "%d attempts left."
	attemptLeftOne       = "1 attempt left."
)

// Exported for the windows that show them without a view model.
const (
	PlanTitle        = planTitle
	PlanPreparing    = progressPreparing
	PlanDetailsTitle = "Backup plan details"
	PlanColumnFolder = "Folder"
	PlanColumnType   = "Type"
	PlanColumnWhy    = "Why"
	PlanColumnAbout  = "About"
	ButtonCancel     = buttonCancel
	ButtonCopy       = "Copy"
	ButtonCopied     = "Copied"
	LogTitle         = "Log"
	DetailsOfResult  = "Details"
)

// Restore backup page (GUI spec 7).
const (
	columnFolder        = "Folder"
	columnType          = "Type"
	columnBasedOn       = "Based on"
	columnSize          = "Size"
	columnChain         = "Chain"
	columnStatus        = "Status"
	filterAll           = "All folders"
	filterOld           = "Old: %s"
	chainOne            = "1 chain"
	chainMany           = "%d chains"
	nextRemoves         = "If your next backup succeeds, it removes %s (%s): %s."
	buttonOpenBackupDir = "&Open backup folder"
	legacyLine          = "%s files from RestoreSafe 1.x are in the backup folder. RestoreSafe 2 can't restore them; keep RestoreSafe 1.0.2 for that. They're never changed."
	leftoverLine        = "Leftovers of an interrupted backup (%s files) are removed by the next backup."
	runFailed           = "%s · Backup failed"
	runCancelled        = "%s · Backup cancelled before a folder was backed up"
	runIncomplete       = "Unfinished backups of %s"
	runNoSets           = "No folder was backed up. The log says why."
	tipCreated          = "Created %s"
	tipBasedOn          = "Based on %s"
	runPartCancelled    = "cancelled"
	runPartFailed       = "failed"
	runPartNewKeys      = "new keys"
	warningOne          = "1 warning"
	warningMany         = "%d warnings"
	statusComplete      = "Complete"
	statusIncomplete    = "Incomplete"
	statusBaseMissing   = "Full backup missing"
	statusDamaged       = "Damaged"
	statusSkippedOne    = "1 skipped file"
	statusSkipped       = "%s skipped files"
	statusVerified      = "Verified %s"
	statusVerifying     = "Verifying"
	statusVerifyingPct  = "Verifying, %d%%"
	basedOnFullShort    = "FULL of %s"
	basedOnNone         = "missing"
	reasonIncomplete    = "This backup is incomplete."
	reasonBaseMissing   = "Its full backup is missing."
	selectionHint       = "Select a backup to restore or verify it."
	selectionRun        = "Backup of %s (%s)"
	selectionLogOnly    = "%s: no backup was written. The log says why."
	setDiffOf           = "%s, differential %s of %s"
	setFullOf           = "%s, full backup of %s"
	buttonRestore       = "&Restore…"
	buttonVerify        = "&Verify…"
	VerifyTitle         = "Verify"
	VerifyDetailsTitle  = "Verification details"
	verifyHeading       = "Verify %s from the backup of %s"
	verifyReadLabel     = "Read"
	verifyReadText      = "About %s to read · nothing is written"
	verifyChecks        = "Every file is decrypted and checked against its checksum."
	verifyReadsBase     = "Differentials are read with their full backup of %s."
	verifyReadsBasesOf  = "Differentials are read with their full backups of %s."
	verifyReadsBases    = "Differentials are read with their full backups."
	verifyHiddenOne     = "The folder filter on Restore backup hides 1 other folder of this backup. Choose All folders to verify it too."
	verifyHidden        = "The folder filter on Restore backup hides %d other folders of this backup. Choose All folders to verify them too."
	logTitleFile        = "Log (%s)"
	logTitleOf          = "Log of %s (%s)"
	linkRunLog          = "Show log"
	logFilterAll        = "&All"
	logFilterWarnings   = "&Warnings and errors"
	buttonOpenLog       = "Open in &Editor"
	logNoWarnings       = "No warnings or errors in this log."
)

// Names screen readers announce, and the list's menu.
const (
	FilterName      = "Folder filter"
	BackupsListName = "Backups"
	menuRestoreText = "&Restore…"
	menuVerifyText  = "&Verify…"
	menuShowLog     = "Show &log"
	menuCopyName    = "&Copy set name"
	menuOpenFolder  = "&Open backup folder"
)

// Restore window (GUI spec 8), worded like the backup plan (6.1).
const (
	RestoreTitle         = "Restore"
	RestoreTo            = "To"
	RestoreBrowse        = "B&rowse…"
	RestoreIntoBackupDir = "Restore into the backup directory"
	RestoreDetailsTitle  = "Restore details"
	ColumnCheck          = "Check"
	restoreHeading       = "Restore %s from the backup of %s"
	restoreHeadingNone   = "Restore from the backup of %s"
	restoreNote          = "Whole folders are restored, and every file is checked against its checksum. To get a single file back, restore its folder to a new place and copy the file."
	hintChooseFolder     = "Choose at least one folder."
	unrestorableOne      = "%s can't be restored: its full backup is missing."
	unrestorableMany     = "%s can't be restored: their full backups are missing."
	destHintEmpty        = "Enter or browse to the folder to restore into."
	destHintFullPath     = `Enter a full path, such as D:\Restore.`
	destNew              = "New folder"
	destExists           = "Already exists"
	destExistsOne        = "Choose another place, or rename or move the folder that already exists."
	destExistsMany       = "Choose another place, or rename or move the folders that already exist."
	destInvalid          = "Can't be created"
	destInvalidLine      = "%s can't be created: %s"
	unlockOrRecovery     = ", or recovery code"
	restoredLine         = "About %s to %s in %s."
	restoreEveryFile     = "Every file matched its checksum."
	restoreSkippedOne    = "%s: 1 file isn't in this backup. It couldn't be read when the backup was made; the log names it."
	restoreSkipped       = "%s: %s files aren't in this backup. They couldn't be read when the backup was made; the log names them."
	restoreStaleOne      = "%s: 1 file is restored in an older version from %s. It couldn't be read when the backup was made; the log names it."
	restoreStale         = "%s: %s files are restored in an older version from %s. They couldn't be read when the backup was made; the log names them."
	resultIncomplete     = "Restore incomplete"
	restoreIncompleteDir = "%s is incomplete; don't use it as a full copy."
	restoreNotRestored   = "%s wasn't restored."
	restoreNotRestoredN  = "%s weren't restored."
	restoreKept          = "%s was restored."
	restoreKeptN         = "%s were restored."
	restoreVerifyHint    = "Verify this backup, or restore from an older one."
	buttonOpenFolder2    = "&Open folder"
	progressRestoring    = "%s · %s"
	restoringFull        = "full backup"
	restoringDiff        = "differential %d, with its full backup of %s"
)

// Settings page (GUI spec 10).
const (
	buttonReload        = "Re&load"
	reasonReloadBusy    = "Reload waits until the running operation has finished."
	settingsReloadNote  = "After saving your changes in the editor, click Reload."
	missingOne          = "%s isn't in config.yaml, so its default applies."
	missingMany         = "%d settings aren't in config.yaml, so their defaults apply: %s."
	buttonAddMissing    = "&Add to config.yaml"
	reasonAddBusy       = "Adding waits until the running operation has finished."
	missingAdded        = "The missing settings were added with their defaults. The previous file is saved as %s."
	settingsFolders     = "Folders to back up"
	settingNothing      = "Nothing"
	settingLeaveOut     = "Leave out"
	settingUnreadable   = "Unreadable files"
	unreadableStop      = "Stop the backup of that folder"
	unreadableSkip      = "Skip the file and warn"
	settingSplit        = "Split files"
	splitAt             = "At %s"
	cardDifferential    = "Full and differential"
	settingDiffs        = "Differential backups"
	settingFullAfter    = "New full backup after"
	settingOrWhen       = "or when"
	daysCount           = "%d days"
	diffReaches         = "a differential reaches %d%% of its full backup"
	cardRetention       = "Retention"
	settingKeep         = "Keep"
	settingKeepDiffs    = "Differentials"
	keepEverything      = "All backups"
	keepAllChains       = "All chains"
	keepDefault         = " (the default; %s recommended)"
	recommendedKeep     = 3
	keepNChains         = "%s per folder"
	keepAllDiffs        = "All of a chain"
	keepNDiffs          = "%d per chain"
	retentionRuns       = "Runs after each successful backup; skipped after a failed verification or when the newest backup has skipped files."
	cardChecks          = "Checks"
	settingVerifyAfter  = "Verify each backup after it's written"
	settingReminder     = "Reminder"
	reminderAfter       = "After %d days without a backup"
	cardKeysUnlock      = "Keys and unlocking"
	settingUnlock       = "Unlock with"
	settingSpare        = "Spare YubiKey"
	settingRecovery     = "Recovery code"
	settingPwLength     = "New passwords"
	atLeastChars        = "At least %d characters"
	linkArgon2          = "Key derivation (Argon2id)"
	settingArgonTime    = "Passes"
	settingArgonMemory  = "Memory"
	settingArgonThreads = "Threads"
	argon2Note          = "Changes apply to new keys only."
	cardLogging         = "Logging"
	settingLogLevel     = "Log level"
	settingIODiag       = "I/O diagnostics"
	settingOn           = "On"
	settingOff          = "Off"
	folderFound         = "Found"
	folderNotFound      = "Not found"
	folderUnreadable    = "Can't be read"
	dirUnreachable      = "Not reachable"
	dirNotWritable      = "Can't be written"
	dirReachable        = "Reachable"
	dirReachableFree    = "Reachable, %s free"
)
